CREATE DATABASE vcs;

CREATE TABLE IF NOT EXISTS vcs."users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(20) UNIQUE NOT NULL,
  "password" varchar(225) NOT NULL,
  "full_name" varchar(50) NOT NULL,
  "phone" varchar(11) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS vcs."contracts" (
  "contract_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contract_code" varchar(20) NOT NULL,
  "limit_amount" numeric,
  "phone" varchar(11) NOT NULL,
  "is_active" bool,
  "created_date" timestamp
);

CREATE TABLE IF NOT EXISTS vcs."consumption_records" (
  "consumption_record_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contract_id" bigint,
  "income_month" numeric,
  "total_income" numeric,
  "balance" numeric,
  "is_paid" bool,
  "created_date" timestamp,
  "price_per_kwh" float
);

CREATE TABLE IF NOT EXISTS vcs."consumption_record_details" (
  "consumption_record_detail_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consumption_record_id" bigint,
  "kwh_number" float,
  "image_url" varchar(255),
  "type" int,
  "created_date" timestamp
);

CREATE TABLE IF NOT EXISTS vcs."transactions" (
  "transaction_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consumption_record_id" bigint,
  "payment_method" varchar(20),
  "amount" float,
  "created_date" timestamp,
  "vnp_txn_ref" varchar(50),
  "vnp_transaction_no" varchar(50),
  "bank_code" varchar(20)
);

CREATE TABLE IF NOT EXISTS vcs."error_log" (
  "error_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "error_code" varchar(10),
  "error_api" varchar(20),
  "error_reason" varchar(225),
  "created_date" timestamp
);

CREATE TABLE IF NOT EXISTS vcs."password_reset_otp" (
  "password_reset_otp_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(100) NOT NULL,
  "otp_code" varchar(6) NOT NULL,
  "expiry_date" timestamp NOT NULL,
  "reset_token" varchar(36),
  "used" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS vcs."unit_price" (
  "unit_price_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "price_per_kwh" float NOT NULL,
  "created_date" timestamp default now()
);

CREATE INDEX IF NOT EXISTS idx_password_reset_otp_email ON password_reset_otp(email);
CREATE INDEX IF NOT EXISTS idx_password_reset_otp_otp_code ON password_reset_otp(otp_code);
CREATE INDEX IF NOT EXISTS idx_password_reset_otp_reset_token ON password_reset_otp(reset_token);

-- Foreign key constraints
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_consumption_records_contract') THEN
    ALTER TABLE vcs."consumption_records" 
      ADD CONSTRAINT fk_consumption_records_contract
      FOREIGN KEY ("contract_id") REFERENCES vcs."contracts" ("contract_id");
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_consumption_record_details_consumption_records') THEN
    ALTER TABLE vcs."consumption_record_details" 
      ADD CONSTRAINT fk_consumption_record_details_consumption_records
      FOREIGN KEY ("consumption_record_id") REFERENCES vcs."consumption_records" ("consumption_record_id");
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transactions_consumption_records') THEN
    ALTER TABLE vcs."transactions" 
      ADD CONSTRAINT fk_transactions_consumption_records
      FOREIGN KEY ("consumption_record_id") REFERENCES vcs."consumption_records" ("consumption_record_id");
  END IF;
END $$;
